[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cd server && npm install --legacy-peer-deps",
  "cd client && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd client && DISABLE_ESLINT_PLUGIN=true SKIP_PREFLIGHT_CHECK=true TSC_COMPILE_ON_ERROR=true CI=false npm run build"
]

[start]
cmd = "node server/server.js"
